server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cinehub_db
logging:
  level:
    org:
      springframework:
        data:
          mongodb: INFO
      mongodb: INFO

