server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cinehub_db

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.kientran: INFO

tmdb:
  api:
    key: ${API_KEY}
    base-url: https://api.themoviedb.org/3
  image:
    base-url: https://image.tmdb.org/t/p/

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 300000
  refresh-token-expiration-ms: 604800000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  avatar:
    folder: avatars