server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cinehub_db
  logging:
    level:
      org:
        springframework:
          data:
            mongodb: INFO
        mongodb: INFO

tmdb:
  api:
    key: ${API_KEY}
    base-url: https://api.themoviedb.org/3
  image:
    base-url: https://image.tmdb.org/t/p/

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 300000
  refresh-token-expiration-ms: 604800000