server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cinehub_db
  logging:
    level:
      org:
        springframework:
          data:
            mongodb: INFO
      com: # Thêm cấu hình log cho gói của bạn
        kientran: INFO

tmdb:
  api:
    key: ${API_KEY}
    base-url: https://api.themoviedb.org/3
  image:
    base-url: https://image.tmdb.org/t/p/

jwt:
  secret: 4a5c0d5096d722509cf26a3c621b5770810c5bfc233a02e953f3d299c4335148
  access-token-expiration-ms: 300000
  refresh-token-expiration-ms: 604800000